const data =[
  {
    id:"1",
    img: "https://m.media-amazon.com/images/I/71pfwyNt66L._AC_SX535_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    priceRange: "$150-$200",
    isHot:"true",
    percent: "21%ON"
  },
  {
    id:"2",
    img: "https://m.media-amazon.com/images/I/61aXSkFNTUL._AC_SY535_.jpg",
    title: "Adidas Ultraboost 22",
    reviews: "(98 reviews)",
    prevPrice: "$180.00",
    newPrice: "150",
    company: "Adidas",
    color: "black",
    category: "running",
    priceRange: "$100-$150",
    isHot:"true",
    percent: "8%OFF"
  },
  {
    id:"3",
    img: "https://m.media-amazon.com/images/I/5196Txr-BeL._AC_SY535_.jpg",
    title: "Puma RS-X Reinvent",
    reviews: "(76 reviews)",
    prevPrice: "$130.00",
    newPrice: "110",
    company: "Puma",
    color: "blue",
    category: "sneakers",
    priceRange: "$100-$150",
    isHot:"false",
     percent: "7%OFF"
  },
  {
    id:"5",
    img: "https://m.media-amazon.com/images/I/71FEnjTLuWL._AC_SY535_.jpg",
    title: "Reebok Classic Leather",
    reviews: "(54 reviews)",
    prevPrice: "$120.00",
    newPrice: "95",
    company: "Reebok",
    color: "white",
    category: "classic",
    priceRange: "$50-$100",
    isHot:"false",
     percent: "10%OFF"
  },
  {
    id:"6",
    img: "https://m.media-amazon.com/images/I/71WSLlYWnEL._AC_SX535_.jpg",
    title: "Vans Old Skool",
    reviews: "(210 reviews)",
    prevPrice: "$100.00",
    newPrice: "80",
    company: "Vans",
    color: "black",
    category: "skate",
    priceRange: "$50-$100",
    isHot:"false",
    percent: "5%OFF"
  },
  {
    id:"7",
    img: "https://m.media-amazon.com/images/I/71kvGJoz4OL._AC_SX535_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(300 reviews)",
    prevPrice: "$90.00",
    newPrice: "75",
    company: "Nike",
    color: "yellow",
    category: "casual",
    priceRange: "$50-$100",
    isHot:"true",
    percent: "5%OFF"
  },
  {
    id:"8",
    img: "https://m.media-amazon.com/images/I/71U92sbgHAL._AC_SY535_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(89 reviews)",
    prevPrice: "$110.00",
    newPrice: "85",
    company: "Nike",
    color: "blue",
    category: "sneakers",
    priceRange: "$100-$150",
    isHot:"true",
    percent: "5%OFF"
  },
  {
    id:"9",
    img: "https://m.media-amazon.com/images/I/71qy9tbKD2L._AC_SX535_.jpg",
    title: "Nike Air Max 270 React",
    reviews: "(400 reviews)",
    prevPrice: "$160.00",
    newPrice: "130",
    company: "Nike",
    color: "orange",
    category: "running",
    priceRange: "$100-$150",
     isHot:"true",
     percent: "8%OFF"
  },
  {
    id:"10",
    img: "https://m.media-amazon.com/images/I/71Psj6b1VTL._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(250 reviews)",
    prevPrice: "$150.00",
    newPrice: "120",
    company: "Adidas",
    color: "white",
    category: "sneakers",
    priceRange: "$100-$150",
     isHot:"true",
      percent: "8%OFF"
  },
  {
    id:"11",
    img: "https://m.media-amazon.com/images/I/513YyfoU5OL._AC_SY535_.jpg",
    title: "Puma Suede Classic",
    reviews: "(140 reviews)",
    prevPrice: "$100.00",
    newPrice: "70",
    company: "Puma",
    color: "red",
    category: "casual",
    priceRange: "$50-$100",
     isHot:"true",
      percent: "9%OFF"
  },
  {
    id:"12",
    img: "https://m.media-amazon.com/images/I/81GVeaeDBfL._AC_SY535_.jpg",
    title: "Reebok Nano X2",
    reviews: "(160 reviews)",
    prevPrice: "$140.00",
    newPrice: "115",
    company: "Reebok",
    color: "red",
    category: "training",
    priceRange: "$100-$150",
     isHot:"true",
      percent: "20%OFF"
  },
  {
    id:"13",
    img: "https://m.media-amazon.com/images/I/71ZImhXErAL._AC_SX535_.jpg",
    title: "Vans Authentic",
    reviews: "(190 reviews)",
    prevPrice: "$90.00",
    newPrice: "65",
    company: "Vans",
    color: "blue",
    category: "skate",
    priceRange: "$50-$100",
     isHot:"true",
     percent: "20%OFF"
  },
  {
    id:"14",
    img: "https://m.media-amazon.com/images/I/81zvARaus5L._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(75 reviews)",
    prevPrice: "$95.00",
    newPrice: "70",
    company: "Adidas",
    color: "red",
    category: "casual",
    priceRange: "$50-$100",
     isHot:"true",
     percent: "15%OFF"
  },
  {
    id:"15",
    img: "https://m.media-amazon.com/images/I/51DZmqTlEwL._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(133 reviews)",
    prevPrice: "$160.00",
    newPrice: "135",
    company: "Adidas",
    color: "blue",
    category: "running",
    priceRange: "$100-$150",
     isHot:"false",
     percent: "20%OFF"
  },
  {
    id:"16",
    img: "https://m.media-amazon.com/images/I/81zyl2Lpu2L._SX695_.jpg",
    title: "Nike Blazer Mid '77",
    reviews: "(200 reviews)",
    prevPrice: "$120.00",
    newPrice: "95",
    company: "Nike",
    color: "black",
    category: "classic",
    priceRange: "$50-$100",
    isHot:"false",
    percent: "20%OFF"
  },
  {
    id:"17",
    img: "https://m.media-amazon.com/images/I/71tGKWAOvwL._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(310 reviews)",
    prevPrice: "$110.00",
    newPrice: "90",
    company: "Adidas",
    color: "black",
    category: "classic",
    priceRange: "$50-$100",
    isHot:"false",
    percent: "15%OFF"
  },
  {
    id:"18",
    img: "https://m.media-amazon.com/images/I/61yydh-bKFL._AC_SX535_.jpg",
    title: "Puma Cali Sport",
    reviews: "(60 reviews)",
    prevPrice: "$120.00",
    newPrice: "100",
    company: "Puma",
    color: "white",
    category: "casual",
    priceRange: "$100-$150",
    isHot:"true",
    percent: "10%OFF"
  },
  {
    id:"20",
    img: "https://m.media-amazon.com/images/I/71nGRi3+hzL._AC_UX575_.jpg",
    title: "Reebok Club C 85",
    reviews: "(144 reviews)",
    prevPrice: "$100.00",
    newPrice: "85",
    company: "Reebok",
    color: "white",
    category: "tennis",
    priceRange: "$50-$100",
    isHot:"true",
    percent: "10%OFF"
  },
  {
    id:"21",
    img: "https://m.media-amazon.com/images/I/71QyjVOjohL._AC_SX535_.jpg",
    title: "Vans Sk8-Hi",
    reviews: "(276 reviews)",
    prevPrice: "$110.00",
    newPrice: "95",
    company: "Vans",
    color: "pink",
    category: "skate",
    priceRange: "$50-$100",
    isHot:"true",
    percent: "10%OFF"
  },
  {
    id:"22",
    img: "https://m.media-amazon.com/images/I/61eU4tUFbKL._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(88 reviews)",
    prevPrice: "$130.00",
    newPrice: "105",
    company: "Adidas",
    color: "green",
    category: "platform",
    priceRange: "$100-$150",
    isHot:"true",
    percent: "10%OFF"
  },
   {
    id:"23",
    img: "https://m.media-amazon.com/images/I/81OHsG+kwcL._AC_SX535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(88 reviews)",
    prevPrice: "$43.54",
    newPrice: "71.95",
    company: "Adidas",
    color: "blue",
    category: "platform",
    priceRange: "$50-$100",
    isHot:"false",
    percent: "10%ON"
  },
  {
    id:"24",
    img: "https://m.media-amazon.com/images/I/51yKY+Eu7lL._AC_SY535_.jpg",
    title: "Adidas NMD R1",
    reviews: "(88 reviews)",
    prevPrice: "$119.90",
    newPrice: "105",
    company: "Adidas",
    color: "gray",
    category: "platform",
    priceRange: "$100-$150",
    isHot:"true",
    percent: "5%OFF"
  },
  {
    id:"25",
    img: "https://m.media-amazon.com/images/I/71uEkSxm-ML._AC_SY535_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(88 reviews)",
    prevPrice: "$89.99",
    newPrice: "90.99",
    company: "Nike",
    color: "gray",
    category: "platform",
    priceRange: "$50-$100",
    isHot:"true",
    percent: "1%ON"
  },
   {
    id:"26",
    img: "https://m.media-amazon.com/images/I/71xX+mHmkUL._AC_SX535_.jpg",
    title: "Puma Cali Sport",
    reviews: "(88 reviews)",
    prevPrice: "185.00",
    newPrice: "146.03",
    company: "Puma",
    color: "black",
    category: "platform",
    priceRange: "$150-$200",
    isHot:"true",
    percent: "10%OFF"
  },
   {
    id:"27",
    img: "https://m.media-amazon.com/images/I/71f0XXNRpVL._AC_SX535_.jpg",
    title: "Puma Cali Sport",
    reviews: "(88 reviews)",
    prevPrice: "$170.19",
    newPrice: "150.02",
    company: "Puma",
    color: "white",
    category: "platform",
    priceRange: "$150-$200",
    isHot:"false",
    percent: "10%OFF"
  },
   {
    id:"28",
    img: "https://m.media-amazon.com/images/I/61H9mi6tOQL._AC_SX535_.jpg",
    title: "Puma Cali Sport",
    reviews: "(88 reviews)",
    prevPrice: "$133.00",
    newPrice: "120.03",
    company: "Puma",
    color: "black",
    category: "platform",
    priceRange: "$150-$200",
    isHot:"false",
    percent: "5%OFF"
  },
  {
    id:"29",
    img: "https://m.media-amazon.com/images/I/71+zW8Se0AL._SX625_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(70 reviews)",
    prevPrice: "$140.00",
    newPrice: "120.03",
    company: "Nike",
    color: "red",
    category: "platform",
    priceRange: "$150-$200",
    isHot:"false",
    percent: "10%OFF"
   
  },
   {
    id:"30",
    img: "https://m.media-amazon.com/images/I/61H4UrqqHxL._SX625_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(55 reviews)",
    prevPrice: "$90.00",
    newPrice: "60.03",
    company: "Nike",
    color: "red",
    category: "platform",
    priceRange: "$50-$100",
    isHot:"true",
    percent: "20%OFF"
   
  },
   {
    id:"31",
    img: "https://m.media-amazon.com/images/I/81eXibJNWpL._SX675_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(70 reviews)",
    prevPrice: "$40.00",
    newPrice: "50.03",
    company: "Nike",
    color: "red",
    category: "platform",
    priceRange: "$50-$100",
   isHot:"true",
   percent: "10%ON"
  },
  {
    id:"32",
    img: "https://m.media-amazon.com/images/I/81NUHJxVeML._SX625_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(40 reviews)",
    prevPrice: "$80.00",
    newPrice: "27.03",
    company: "Nike",
    color: "red",
    category: "platform",
    priceRange: "$25-$50",
   isHot:"true",
   percent: "25%OFF"
  },
   {
    id:"33",
    img: "https://m.media-amazon.com/images/I/818dryBJPdL._SX695_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(35 reviews)",
    prevPrice: "$80.00",
    newPrice: "29.03",
    company: "Nike",
    color: "blue",
    category: "platform",
    priceRange: "$25-$50",
    isHot:"true",
    percent: "30%OFF"
   
  },
   {
    id:"34",
    img: "https://m.media-amazon.com/images/I/71LIWJ-zNaL._SX695_.jpg",
    title: "Nike Air Monarch IV ",
    reviews: "(35 reviews)",
    prevPrice: "$80.00",
    newPrice: "29.03",
    company: "Nike",
    color: "white",
    category: "platform",
    priceRange: "$25-$50",
    isHot:"true",
    percent: "30%OFF"
   
  },
  {
    id:"35",
    img: "https://m.media-amazon.com/images/I/71RYJAai8PL._SX695_.jpg",
    title: "Puma Cali Sport ",
    reviews: "(30 reviews)",
    prevPrice: "$80.00",
    newPrice: "29.03",
    company: "Puma",
    color: "blue",
    category: "platform",
    priceRange: "$25-$50",
    isHot:"true",
    percent: "30%OFF"
  },

];
export default data;